version: "2"

services:
  # プロキシサーバ
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: true # ルート権限
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro # letsencryptコンテナがSSL証明書を ./certs/ に作成
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    # restart: always # Dockerサービス起動時に自動起動
    # 他のコンテナを見つけられるようにブリッジモードにする（見つけて欲しいコンテナもブリッジモードにする）
    ## もしくは共有のネットワークを作成する
    network_mode: bridge

  # 無料SSL証明書発行
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx-proxy
    # restart: always # Dockerサービス起動時に自動起動
    network_mode: bridge
  
  # アプリケーション側Dockerコンテナに必要な環境変数
  # - VIRTUAL_HOST: example.com
  # - VIRTUAL_PORT: 80
  # - LETSENCRYPT_HOST: example.com
  # - LETSENCRYPT_EMAIL: admin@example.com
  # ローカル開発時に必要な環境変数
  # - CERT_NAME: default
