# リバースプロキシ専用Docker
version: "2"
services:
  # リバースプロキシ
  proxy:
    image: jwilder/nginx-proxy
    privileged: true
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./.certs:/etc/nginx/certs
    restart: always
    # 他のコンテナを見つけられるようにブリッジモードにする
    # 逆に、見つけて欲しいコンテナもブリッジモードにする
    network_mode: bridge
