version: "3"

services:
  web:
    build: ./web
    links:
      - db # dbコンテナとリンク
      - mailhog # mailhogコンテナとリンク
    volumes:
      # 共有ディレクトリ
      - ./html:/var/www/html # ドキュメントルート
      # virtualhost設定ファイル
      - ./web/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # php設定ファイルを共有
      - ./web/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 1000:80 # localhost:1000 => container.web:80 (nginx-proxyコンテナを使っているならポート設定は不要)
    # コンテナ内のApache実行ユーザー`www-data`のユーザーIDを環境変数`UID`に変更してApache起動
    command: bash -c 'usermod -o -u ${UID} www-data; groupmod -o -g ${UID} www-data; apachectl -D FOREGROUND'
    network_mode: bridge
    environment:
      # dbコンテナのDBに接続するための環境設定
      DB_HOST: mysql
      DB_DATABASE: web
      DB_USERNAME: root
      DB_PASSWORD: root
      # VIRTUAL_HOST設定（nginx-proxy）
      VIRTUAL_HOST: devel.localhost # localhost:1000 の代わりに devel.localhost でアクセス可能に
      VIRTUAL_PORT: 80
      # mailhogコンテナに接続するための環境設定
      # MAIL_DRIVER: smtp
      # MAIL_HOST: mailhog
      # MAIL_PORT: 1025
      # MAIL_ENCRYPTION: null
  db:
    build: ./db
    volumes:
      # DB永続化
      - db-data:/var/lib/mysql
      # 起動時にinitdb.d内で定義されたデータベースを構築する
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web
  pma:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 2000:80
    network_mode: bridge
    environment:
      PMA_HOST: db
      # VIRTUAL_HOST設定（nginx-proxy）
      VIRTUAL_HOST: pma.devel.localhost # localhost:2000 の代わりに pma.devel.localhost でアクセス可能に
      VIRTUAL_PORT: 80
    links:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - 3000:8025 # HTTP Port (nginx-proxyコンテナを使っているならポート設定は不要)
      # - 4000:1025 # SMTP Port
    network_mode: bridge
    environment:
      # VIRTUAL_HOST設定（nginx-proxy）
      VIRTUAL_HOST: mail.devel.localhost # localhost:3000 の代わりに mail.devel.localhost でアクセス可能に
      VIRTUAL_PORT: 8025
volumes:
  db-data:
    driver: local
