version: '3'

services:
  web:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./html:/var/www/html:cached
    links:
      - db
  #  network_mode: bridge
  #  environment:
  #    VIRTUAL_HOST: local-sirobako.jp
  #    VIRTUAL_PORT: 3000
  db:
    image: mysql:5.7
    network_mode: bridge
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  bundle:
  mysql_data:
