version: "3"

volumes:
  db-data:
services:
  web:
    build: ./web/
    links:
      - db
      - mailhog
    volumes:
      - ./web-data/:/var/www/web-data/
      - ./web/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./web/php.ini:/usr/local/etc/php/php.ini
    command: bash -c 'usermod -o -u ${UID} www-data; groupmod -o -g ${UID} www-data; apachectl -D FOREGROUND'
    network_mode: bridge
    environment:
      VIRTUAL_HOST: ec-cube3.localhost
  db:
    build: ./db/
    volumes:
      - db-data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d/
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ec
  pma:
    image: phpmyadmin/phpmyadmin:latest
    network_mode: bridge
    environment:
      PMA_HOST: db
      VIRTUAL_HOST: pma.ec-cube3.localhost
  mailhog:
    image: mailhog/mailhog
    network_mode: bridge
    environment:
      # VIRTUAL_HOST設定（nginx-proxy）
      VIRTUAL_HOST: mail.ec-cube3.localhost
      VIRTUAL_PORT: 8025
  # proxy:
  #   image: jwilder/nginx-proxy
  #   privileged: true
  #   ports:
  #     - "80:80" # http
  #     - "443:443" # https
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
