version: '3'

services:
  web:
    build: ./web
    tty: true
    privileged: true
    volumes:
      - ./html:/var/www/html:cached
    links:
      - db
    network_mode: bridge
    environment:
      VIRTUAL_HOST: local-dev.jp
  db:
    image: mysql:5.7
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: sirolab
      MYSQL_DATABASE: sirolab
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  bundle:
  mysql_data:
