version: '3'

# Python 3.7 + JupyterNotebook + Julia 1.2 環境
services:
  jupyter:
    build: ./jupyter
    ports:
      - 8888:8888 # http://localhost:8888/?token=julia でアクセス可能に
    volumes:
      - ./app:/var/www/app
    stdin_open: true
    tty: true
    command: jupyter notebook --ip=0.0.0.0 --allow-root
    network_mode: bridge
    environment:
      # nginx-proxyコンテナを使っている場合に使えるvhosts設定
      VIRTUAL_HOST: jupyter.localhost # http://jupyter.localhost/?token=julia でアクセス可能に
      VIRTUAL_PORT: 8888
